### ISSUE TITLE
修复jd_jdzz.js报错获取互助码脚本添加闪购盲盒互助码

### ISSUE THREAD

**Issue by OneYX** [OneYX/jd_scripts#806]
&#20462;&#22797;jd_jdzz.js&#25253;&#38169;&#12290;&#33719;&#21462;&#20114;&#21161;&#30721;&#33050;&#26412;&#28155;&#21152;&#38378;&#36141;&#30450;&#30418;&#20114;&#21161;&#30721;<br>
https://ift.tt/3qJIZei<br>
<pre style="white-space:pre-wrap;width:81ex;">&#20462;&#22797;jd_jdzz.js&#25253;&#38169;&#12290;&#33719;&#21462;&#20114;&#21161;&#30721;&#33050;&#26412;&#28155;&#21152;&#38378;&#36141;&#30450;&#30418;&#20114;&#21161;&#30721;</pre>
<br>
<br>
via Recent Commits to jd_scripts:master https://ift.tt/3qyqIk7<br>
January 26, 2021 at 10:19AM

**Comment by huairen306** [comment]
东东农场好友互助码】6c9ee5fa7c5949068d258b6215d9363f
东东工厂好友互助码】T0189qFyRxgf8FXXIB_ykQCjVWnYaS5kRrbA
东东萌宠好友互助码】MTE1NDUwMTI0MDAwMDAwMDQwNzU4MTUz
京东种豆得豆好友互助码】ki2jlm5ur7a6yszvkno6tvq4ebyzgy7kd77dlwi
京喜工厂好友互助码】AumascldfZT02ELAN2WbtQ==
京东种豆得豆好友互助码】itydhgvalp6sjjutno3uothcwi
京喜工厂好友互助码】Jo_LQ4xl-maA8cS38dwBLg==

东东农场好友互助码】9a5790e4378842989775da4a12f09ee5
东东工厂好友互助码】T0159qFxQhYc91TUIBwCjVWnYaS5kRrbA
东东萌宠好友互助码】MTE1NDAxNzYwMDAwMDAwMzkzMDYxMTU=
京东种豆得豆好友互助码】itydhgvalp6sjjutno3uothcwi
京喜工厂好友互助码】Jo_LQ4xl-maA8cS38dwBLg==
加 我的跟我回我一声音，我加你
